### ISSUE TITLE
HLS code not synthesizing in Vitis_HLS 2022.1/2022.2/2023.1

### ISSUE THREAD

**Issue by francesco-peverelli** [lsq314/SpMM_TCAD#1]
Greetings,

I'm trying to snythesize this design in Vitis_HLS, however I haven't been able to do so, since the kernel fails the dataflow checking. The error reported is:

`Argument 'pong1' failed dataflow checking: it can only be used in one process.`

I get the same error for ping1. I tried synthesizing with Vitis_HLS 2022.1, 2022.2, and 2023.1 and always got this error. Is this a known issue? Please let me know if you have any insights,

Best regards,
Francesco

**Comment by lsq314** [comment]
Hi Francesco,

I have updated the file "pe.cpp" and now the error is solved. You may try it now. But I am a little bit confused that I did not meet this error when I conducted experiments.

Best regards,
Shiqing

**Comment by francesco-peverelli** [comment]
Hi Shiqing,

Thank you for the quick response. It does seem to be synthesizing now!
I'll close the issue,

Best,
Francesco
